[package]
name = "fm-index"
version = "0.1.0"
authors = ["Koki Kato <koki.kato1994@gmail.com>"]
edition = "2018"

[dependencies]
fid = "0.1.3"
num-traits = "0.2"
serde = { version = "1.0", features = ["derive"] }

[dev-dependencies]
rand = "0.6.5"